version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.liferay.portal:com.liferay.portal.impl
    versions:
    - 5.23.12
    - 5.23.13
    - 5.23.14
    - 5.23.16
    - 5.23.17
    - 5.23.18
    - 5.24.0
    - 5.24.1
    - 5.25.0
    - 5.25.1
    - 5.25.2
    - 5.25.3
    - 5.26.0
    - 5.26.1
    - 5.26.2
    - 6.0.0
    - 6.0.4
    - 6.0.5
    - 6.0.6
    - 6.1.0
    - 6.1.2
    - 6.3.0
    - 6.3.1
    - 6.3.3
    - 6.3.4
    - 6.3.5
    - 7.0.1
    - 7.0.3
  - dependency-name: com.liferay.portal:com.liferay.portal.kernel
    versions:
    - 10.0.0
    - 10.0.1
    - 10.0.2
    - 10.1.0
    - 10.1.2
    - 10.2.1
    - 10.2.3
    - 10.3.1
    - 10.4.0
    - 10.5.1
    - 10.6.1
    - 9.23.2
    - 9.24.0
    - 9.25.0
    - 9.27.0
    - 9.27.1
    - 9.28.0
    - 9.28.1
    - 9.29.0
    - 9.30.0
    - 9.31.0
  - dependency-name: com.liferay.portal:com.liferay.util.taglib
    versions:
    - 5.3.5
    - 6.0.0
    - 6.0.1
  - dependency-name: com.liferay.portal:com.liferay.util.java
    versions:
    - 5.0.9
    - 6.0.0
